#!/bin/bash

tput clear

LIBS=" -lbobcat -lcrypto"
GPP="g++ `cat ../../c++std`"

#   Using the standard bobcat library
#CMD="$GPP -o driver -Wall *.cc ${LIBS} -s"

#   Using the library in ../tmp/
CMD="$GPP -o driver -Wall *.cc \
           -L../tmp -ldiffiehellman  ${LIBS} -s"

echo ${CMD}
${CMD}
