#!/bin/bash

# g++ driver.cc -lbobcat

#g++ driver.cc -L../tmp -L../../logbuf/tmp -L../../level/tmp \
#                        -llog -llevel -llogbuf -lbobcat

#g++ driver.cc -L../tmp -L../../logbuf/tmp -llog -llogbuf -lbobcat

g++ driver.o -L../tmp -llog -lbobcat
