#!/bin/bash

GCC="g++ `cat ../../c++std` -o driver"

# # Using the standard bobcat library
# ${GCC} driver.cc -lbobcat

# Using the randbuf library, and bobcat
echo ${GCC} driver.cc -L../../randbuf/tmp -lrandbuf -lbobcat -s
${GCC} driver.cc -L../../randbuf/tmp -lrandbuf -lbobcat -s
