#!/bin/bash


#
# g++ -I. --std=c++2a -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#     -L../../ohexbuf/tmp -L../tmp -lhmacbuf   -lohexbuf
#

tput clear

LIBS=" -lbobcat"

GPP="g++ `cat ../../c++std`"

#   Using the standard bobcat library
CMD="$GPP -o driver -Wall driver.cc ${LIBS} -s"

# #   Using tmp libraries and bobcat
# CMD="$GPP -o driver -Wall -I../../tmp driver.cc \
#     -L../tmp -lifilterbuf \
#     -L../../eoibuf/tmp -leoibuf \
#     -L../../eoi/tmp -leoi \
#     -lbobcat -s"

echo ${CMD}
${CMD}
