#!/bin/bash

#LIBS="-lbobcat -lreadline"
LIBS="-L../tmp -lreadlinehistory -lbobcat -lreadline"
#LIBS="-L../../readlinebuf/tmp -lreadlinebuf -lbobcat -lreadline"

#CMD="g++ `cat ../../c++std` -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib \
#                                                    ${LIBS} -s"

CMD="g++ `cat ../../c++std` -o driver -Wall driver.cc ${LIBS} -s"

echo $CMD
$CMD
