#!/bin/bash

case $1 in
    (a)
        g++ `cat ../../c++std` -o driver *.cc -L../tmp -largconfig -lbobcat -s
    ;;
    (A)
        g++ -g `cat ../../c++std` -o driver *.cc -L../../arg/tmp -L../tmp \
                                        -larg -largconfig -lbobcat -s
    ;;
    (b)
        g++ `cat ../../c++std` -o driver *.cc -lbobcat -s
    ;;
    (*)
    echo $0 a links to the files in the current dir, ../tmp/libargconfig
    echo and bobcat
    echo $0 A links to the files in the current dir, ../../arg/tmp, 
    echo ../tmp/libargconfig, and bobcat
    echo $0 b links to the installed bobcat library
    ;;
esac
