#!/bin/bash

LIB="-lreadline -lbobcat -s"
LIB="-L../tmp -lreadlinebuf -lbobcat  -lreadline -s"

# CMD="g++ --std=c++2a -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib \
#                                                     -lreadline -lbobcat -s"

tput clear

GPP="g++ --std=c++2a"

CMD="$GPP -o driver -Wall driver.cc $LIB"
#    -I../../tmp driver.cc \
#    -L../tmp -lreadlinebuf \
#    -lreadline -lbobcat -s"

echo $CMD
$CMD
