#!/bin/bash

g++ -Wall -odriver driver.cc -lbobcat

exit 0


g++ -Wall -odriver driver.cc -L../../extractorbase/tmp -lextractorbase \
                                -L../tmp -Lcoutextractor -lbobcat
